config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  root 'dashboard#index'

  resources :students

  #login page with form
  get '/login' => 'sessions#new'
 
  #create(post) action for when login for is submitted
  post '/login' => 'sessions#create'

  #delete action to logout
  get '/logout' => 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
	
	has_secure_password

	validates :student_id, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception


    # Make the current_user method available to views also, not just controllers:
	helper_method :current_student

	def current_student
		# Look up the current user based on user_id in the session cookie
		@current_student ||= Student.find(session[:std_id]) if session[:std_id]
	end

	def authorize
		# authroize method redirects user to login page if not logged in:
		redirect_to login_path, alert: 'You must be logged in to access this page' if current_student.nil?
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :authorize, only:[:index]
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		
	end

	def create
	  student = Student.find_by(student_id: params[:login][:student_id].downcase)

	  if student && student.authenticate(params[:login][:password])
	  	session[:std_id] = student.id.to_s
	  	redirect_to root_path, notice: 'Successfully logged in!'
	  else
	  	flash.now.alert = "Incorrect student_id or password, try again."
	  	render :new
	  	
	  end
	end

	def destroy
		session.delete(:std_id)
		redirect_to login_path
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def new
		@student = Student.new
	end

	def create
		@student = Student.create(student_params)

		@student.student_id.downcase

		if @student.

			flash[:notice] = "Account created successfully!"
			redirect_to root_path
		else
			flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid student_id and password and try again."
			render :new
		end
	end

	private

	def student_params
		params.require(:student).permit(:name, :student_id, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Welcome</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simplelogin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <%= notice %>
    <% end %>
  
    <% if alert %>
        <%= alert %>
    <% end %>
  
    <% if current_student %>
      <%= "Logged in as #{current_student.student_id}"%> | <%= link_to "Log Out", logout_path %>
    <% else %>
      <%= link_to "Log In", login_path %> or <%= link_to "Sign Up", new_student_path %> 
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/students/new.html.erb
<%= form_for @student do |f| %>

	<div>
	  <%= f.label :name %>
	  <%= f.text_field :name %>
	</div>

	<div>
	  <%= f.label :student_id %>
	  <%= f.text_field :student_id %>
	</div>

	<div>
	  <%= f.label :password %>
	  <%= f.text_field :password %>
	</div>

	<div>
	  <%= f.label :password_confirmation %>
	  <%= f.text_field :password_confirmation %>
	</div>

	<br>

	<div>
		<%= f.submit "Sign Up" %>
	</div>
	
<% end %>